
[functions.create-pluggy-token]
enabled = true
verify_jwt = true
import_map = "./functions/create-pluggy-token/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-pluggy-token/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-pluggy-token/*.html" ]
